export default {
  ImageBackground: require('../images/bg-main-image.png'),
  bgTarotDeck: require('../images/bgTarotDeck.png'),
  ImgTarotDeck: require('../images/ImgTarotDeck.png'),
  avataDefault: require('../images/avataDefault.png'),
  bgHeaderLogin: require('../images/bg-header-login.png'),
  bgHeaderProfile: require('../images/bg-header-profile.png'),
  imgHeaderRegister: require('../images/img-header-register.png'),
  imgHeaderRegister2: require('../images/img-header-register-2.png'),
  AvatarDemo1: require('../images/avatar-demo-1.png'),
  AvatarDemo2: require('../images/avatar-demo-2.png'),
  imgSettingDecorate: require('../images/imgSettingDecorate.png'),
  imgQrcode: require('../images/imgQrcode.png'),
  hand: require('../images/hand.png'),
  visualImageSl1: require('../images/visualImageSl1.png'),
  visualImageSl2: require('../images/visualImageSl2.png'),
  visualImageSl3: require('../images/visualImageSl3.png'),
  imgArrowUnderChoose: require('../images/imgArrowUnderChoose.png'),
  imgHandDirection: require('../images/imgHandDirection.png'),
  imageLoginTop: require('../images/imageLoginTop.png'),
  visuaforgotpassword: require('../images/visuaforgotpassword.png'),
  iconContinue: require('../images/iconContinue.png'),

  imgTarotCardDefault: require('../images/imgTarotCard.png'),
  imgTarotCardDefault1: require('../images/imgTarotCard1.png'),
  //76 card
  imgTarotCard0: require('../images/cards/0-TheFool.png'),
  imgTarotCard1: require('../images/cards/0-TheFool.png'),
  imgTarotCard2: require('../images/cards/0-TheFool.png'),
  imgTarotCard3: require('../images/cards/0-TheFool.png'),
  imgTarotCard4: require('../images/cards/0-TheFool.png'),
  imgTarotCard5: require('../images/cards/0-TheFool.png'),
  imgTarotCard6: require('../images/cards/0-TheFool.png'),
  imgTarotCard7: require('../images/cards/0-TheFool.png'),
  imgTarotCard8: require('../images/cards/0-TheFool.png'),
  imgTarotCard9: require('../images/cards/0-TheFool.png'),
  imgTarotCard10: require('../images/cards/0-TheFool.png'),
  imgTarotCard11: require('../images/cards/0-TheFool.png'),
  imgTarotCard12: require('../images/cards/0-TheFool.png'),
  imgTarotCard13: require('../images/cards/0-TheFool.png'),
  imgTarotCard14: require('../images/cards/0-TheFool.png'),
  imgTarotCard15: require('../images/cards/0-TheFool.png'),
  
};
